import jsPDF from "jspdf";
import type { RecommendationResult } from "./types";

const COLORS = {
  primary: [30, 58, 95] as [number, number, number],
  accent: [13, 148, 136] as [number, number, number],
  text: [15, 23, 42] as [number, number, number],
  muted: [100, 116, 139] as [number, number, number],
  light: [241, 245, 249] as [number, number, number],
};

export function generatePlanPDF(result: RecommendationResult): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  let y = 15;

  // Header bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageW, 35, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Newcomer Credit Navigator", 15, 18);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Your Personalized Credit Plan", 15, 27);
  y = 45;

  // Profile summary
  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Your Profile", 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.text);

  const profile = result.profile;
  const statusLabels: Record<string, string> = {
    international: "International Student",
    domestic: "Domestic Student",
    pr: "Permanent Resident",
    work_permit: "Work Permit Holder",
  };
  const budgetLabels: Record<string, string> = {
    under_500: "Under $500/mo",
    "500_1000": "$500–$1,000/mo",
    "1000_2000": "$1,000–$2,000/mo",
    over_2000: "Over $2,000/mo",
  };
  const goalLabels: Record<string, string> = {
    cashback: "Cash Back",
    travel_rewards: "Travel Rewards",
    build_credit: "Build Credit Fast",
    low_rates: "Low Interest Rates",
  };

  const profileItems = [
    `Status: ${statusLabels[profile.studentType] ?? profile.studentType}`,
    `Budget: ${budgetLabels[profile.monthlyBudget] ?? profile.monthlyBudget}`,
    `Goal: ${goalLabels[profile.primaryGoal] ?? profile.primaryGoal}`,
    profile.hasGIC ? `GIC Bank: ${profile.gicBank}` : "GIC: None",
  ];

  profileItems.forEach((item) => {
    doc.text(`•  ${item}`, 18, y);
    y += 6;
  });
  y += 6;

  // Recommended Bank
  doc.setFillColor(...COLORS.light);
  doc.roundedRect(15, y - 3, pageW - 30, 28, 3, 3, "F");
  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Recommended Bank", 20, y + 4);
  doc.setFontSize(16);
  doc.text(`${result.topBank.bankName}  —  ${result.topBank.score}% match`, 20, y + 14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.muted);
  doc.text(result.topBank.packageName, 20, y + 21);
  y += 35;

  // Top Credit Cards
  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Top Credit Card Picks", 15, y);
  y += 8;

  result.topCards.forEach((card, i) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    if (i === 0) {
      doc.setFillColor(13, 148, 136);
    } else {
      doc.setFillColor(241, 245, 249);
    }
    doc.roundedRect(15, y - 3, pageW - 30, 22, 2, 2, "F");

    if (i === 0) {
      doc.setTextColor(255, 255, 255);
    } else {
      doc.setTextColor(...COLORS.text);
    }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`#${i + 1}  ${card.cardName}`, 20, y + 5);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`${card.score}% match  •  ${card.bankName}  •  ${card.annualFee}/yr`, 20, y + 12);

    if (card.reasons.length > 0) {
      doc.setFontSize(8);
      if (i === 0) {
        doc.setTextColor(220, 240, 230);
      } else {
        doc.setTextColor(...COLORS.muted);
      }
      doc.text(card.reasons[0], 20, y + 17);
    }

    y += 27;
  });

  y += 5;

  // Personalized Tips
  if (y > 230) {
    doc.addPage();
    y = 20;
  }
  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Your Action Plan", 15, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.text);

  result.personalizedTips.forEach((tip, i) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    const lines = doc.splitTextToSize(`${i + 1}. ${tip}`, pageW - 40);
    doc.text(lines, 18, y);
    y += lines.length * 5 + 3;
  });

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setDrawColor(...COLORS.light);
  doc.line(15, y - 5, pageW - 15, y - 5);
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text("Generated by Newcomer Credit Navigator  •  For educational purposes only", 15, y);

  doc.save("my-credit-plan.pdf");
}
