import type { BankWithStudentCards } from "./types";

/**
 * Student credit cards by bank. Issued to newcomers (international students) with no credit history.
 * No Apply / Learn more — for comparison only. Applying triggers a hard inquiry (see Credit 101).
 */
export const BANKS_WITH_STUDENT_CARDS: BankWithStudentCards[] = [
  {
    id: "cibc",
    name: "CIBC",
    cardCount: 5,
    cards: [
      {
        id: "cibc-adapta",
        name: "CIBC Adapta™ Mastercard® for Students",
        tag: "Most popular",
        headline: "Join and earn up to $150 in value with no annual fee.",
        bullets: [
          "Start building your credit history and automatically earn bonus points in your top 3 spend categories each month.",
          "1.5 Adapta points per $1 spent in your top 3 spend categories (e.g. clothing, e-games, subscriptions, dining); or 2 points per $1 on eligible travel through CIBC by Expedia; or 1 point per $1 on all other purchases.",
          "Includes membership to roadside assistance (towing, battery boosting, gas delivery, etc.).",
        ],
        annualFee: "$0",
        purchaseRate: "21.99%",
        cashRate: "22.99%",
        cashRateQuebec: "21.99%",
      },
      {
        id: "cibc-dividend",
        name: "CIBC Dividend® Visa* Card for Students",
        headline: "Join and earn up to $125 cash back.",
        bullets: [
          "Student budgets go further with cash back on groceries, transportation and daily essentials.",
          "2% cash back on eligible groceries.",
          "1% cash back on eligible gas, electric vehicle charging, transportation, recurring payments and eligible travel through CIBC by Expedia.",
          "Free SPC+ membership; Extended warranty; Pay in installments.",
        ],
        annualFee: "$0",
        purchaseRate: "21.99%",
        cashRate: "22.99%",
        cashRateQuebec: "21.99%",
      },
      {
        id: "cibc-aventura",
        name: "CIBC Aventura® Visa* Card for Students",
        headline: "Earn up to 12,500 Aventura Points for no annual fee.",
        bullets: [
          "Flexible travel rewards program.",
          "1 point per $1 on travel booked through the CIBC Rewards Centre.",
          "1 point per $1 on eligible gas, electric vehicle charging, grocery and drugstore purchases.",
          "Free SPC+ membership; CIBC Pace It™ Installment Plans.",
        ],
        annualFee: "$0",
        purchaseRate: "21.99%",
        cashRate: "22.99%",
        cashRateQuebec: "21.99%",
      },
      {
        id: "cibc-aeroplan",
        name: "CIBC Aeroplan® Visa* Card for Students",
        headline: "Apply and earn up to $200 in value, including up to 10,000 Aeroplan points.",
        bullets: [
          "No annual fee travel card that turns everyday purchases into travel.",
          "1 point per $1 with Air Canada and Air Canada Vacations®.",
          "1 point per $1 on eligible gas, electric vehicle charging and groceries.",
          "Preferred pricing; Earn points twice at over 170 retailers.",
        ],
        annualFee: "$0",
        purchaseRate: "21.99%",
        cashRate: "22.99%",
        cashRateQuebec: "21.99%",
      },
      {
        id: "cibc-classic",
        name: "CIBC Classic Visa* Card for Students",
        headline: "90-day protection on new purchases. Send money abroad with $0 transfer fee (CIBC Global Money Transfer™).",
        bullets: [
          "Free SPC+ membership; CIBC Pace It™ Installment Plans.",
          "Save up to 10 cents per litre on gas with CIBC and Journie Rewards.",
        ],
        annualFee: "$0",
        purchaseRate: "21.99%",
        cashRate: "22.99%",
        cashRateQuebec: "21.99%",
      },
    ],
  },
  {
    id: "scotiabank",
    name: "Scotiabank",
    cardCount: 5,
    cards: [
      {
        id: "scotia-scene",
        name: "Scotiabank® Scene+™ Visa* Card (for students)",
        headline: "Earn up to 10,000 bonus Scene+ points within your first 3 months.",
        bullets: [
          "Earn 2 Scene+ points on every $1 at Sobeys, Safeway, Foodland & Participating Co-ops, FreshCo and more.",
          "Earn 2 Scene+ points on every $1 at Home Hardware.",
        ],
        annualFee: "$0",
        purchaseRate: "20.99%",
        cashRate: "22.99%",
      },
      {
        id: "scotia-momentum-nofee",
        name: "Scotia Momentum® No-Fee Visa* Card (for students)",
        headline: "Earn 10% Cash Back on all purchases for the first 3 months (up to $2,000 in total purchases).",
        bullets: [
          "0% introductory interest rate on balance transfers for the first 6 months (2% fee per cash advance; 22.99% after; annual fee $0).",
        ],
        annualFee: "$0",
        purchaseRate: "20.99%",
        cashRate: "22.99%",
      },
      {
        id: "scotia-momentum",
        name: "Scotia Momentum® Visa* Card (for students)",
        headline: "2.99% introductory interest rate on balance transfers for the first 6 months (22.99% after).",
        bullets: [],
        annualFee: "$49",
        purchaseRate: "20.99%",
        cashRate: "22.99%",
      },
      {
        id: "scotia-amex",
        name: "Scotiabank American Express® Card (for students)",
        headline: "Earn up to 5,000 bonus Scene+ points within your first 3 months (up to $50 towards travel).",
        bullets: [
          "Earn 3 Scene+ points on every $1 at Sobeys, Safeway, FreshCo, Foodland and more.",
        ],
        annualFee: "$0",
        purchaseRate: "19.99%",
        cashRate: "22.99%",
      },
      {
        id: "scotia-value",
        name: "Scotiabank Value® Visa* Card (for students)",
        headline: "Save on interest. 0.99% introductory rate on balance transfers for the first 9 months (2% fee; 13.99% after). No annual fee in the first year.",
        bullets: [],
        annualFee: "$29",
        purchaseRate: "13.99%",
        cashRate: "13.99%",
      },
    ],
  },
  {
    id: "bmo",
    name: "BMO",
    cardCount: 1,
    cards: [
      {
        id: "bmo-cashback-student",
        name: "Student BMO CashBack® Mastercard®",
        tag: "Student · No fee",
        headline: "Welcome offer: Get 5% cash back in your first 3 months.",
        bullets: [
          "Designed for students; build credit with no annual fee.",
          "Cash back on everyday purchases.",
        ],
        annualFee: "$0",
        purchaseRate: "21.99%",
        cashRate: "23.99%",
        cashRateQuebec: "21.99%",
      },
    ],
  },
  {
    id: "td",
    name: "TD",
    cardCount: 3,
    cards: [
      {
        id: "td-cashback",
        name: "TD Cash Back Visa* Card",
        tag: "Special offer",
        headline: "Earn up to $100 in Cash Back Dollars when you spend $1,000+ in the first 3 months (one-time payout after 3 months). Account must be opened and approved by May 4, 2026.",
        bullets: [],
        annualFee: "$0",
        purchaseRate: "21.99%",
        cashRate: "22.99%",
      },
      {
        id: "td-rewards",
        name: "TD Rewards Visa* Card",
        tag: "Special offer",
        headline: "Earn a value of $50 in TD Rewards Points to use on eligible Amazon.ca purchases, plus no annual fee. Conditions apply.",
        bullets: [],
        annualFee: "$0",
        purchaseRate: "21.99%",
        cashRate: "22.99%",
      },
      {
        id: "td-lowrate",
        name: "TD Low Rate Visa* Card",
        headline: "0% promotional interest rate on purchases for the first 6 months from account opening. Conditions apply.",
        bullets: [],
        annualFee: "$25",
        purchaseRate: "12.90%",
        cashRate: "12.90%",
      },
    ],
  },
  {
    id: "rbc",
    name: "RBC",
    cardCount: 5,
    cards: [
      {
        id: "rbc-ion-plus",
        name: "RBC ION+ Visa",
        tag: "Special offer",
        headline: "Get up to 21,000 Avion points — up to $150 of value in gift cards. Apply by May 6, 2026. Students or anyone 24 and younger receive an annual fee rebate.",
        bullets: [
          "Earn 3X Avion points per $1 on groceries, gas, dining, food delivery, rideshare, streaming and more.",
          "Earn 1X Avion point per $1 on all other qualifying purchases.",
          "Mobile device insurance, purchase security and extended warranty coverage.",
          "Additional card: $0.",
        ],
        annualFee: "$48",
        purchaseRate: "20.99%",
        cashRate: "22.99%",
      },
      {
        id: "rbc-cashback",
        name: "RBC Cash Back Mastercard",
        tag: "Limited time offer",
        headline: "Get up to 7% cash back for the first 3 months on up to $1,000 in total purchases. Apply by March 25, 2026.",
        bullets: [
          "Earn up to 2% cash back on grocery store purchases; up to 1% on all other qualifying purchases.",
          "Instant fuel savings of 3¢/L when using a linked card at Petro-Canada.",
          "3-month complimentary DashPass subscription plus $0 delivery fees.",
          "Additional card: $0.",
        ],
        annualFee: "$0",
        purchaseRate: "20.99%",
        cashRate: "22.99%",
      },
      {
        id: "rbc-ion",
        name: "RBC ION Visa",
        tag: "Special offer",
        headline: "Get up to 11,000 Avion points — up to $75 of value in gift cards. Apply by May 6, 2026.",
        bullets: [
          "Earn 1.5X Avion points per $1 on groceries, gas, streaming and more.",
          "Earn 1X Avion point per $1 on all other qualifying purchases.",
          "Purchase security and extended warranty coverage.",
          "Additional card: $0.",
        ],
        annualFee: "$0",
        purchaseRate: "20.99%",
        cashRate: "22.99%",
      },
      {
        id: "rbc-westjet",
        name: "WestJet RBC Mastercard",
        tag: "Offer available",
        headline: "Get up to 10,000 WestJet points (value of up to $100 off travel). No minimum income required to apply.",
        bullets: [
          "Earn 1 WestJet point per $1 on everyday purchases; 1.5 points per $1 on WestJet flights and packages.",
          "Annual round-trip companion voucher.",
          "Travel benefits and insurance.",
          "Additional card: $19.",
        ],
        annualFee: "$39",
        purchaseRate: "20.99%",
        cashRate: "22.99%",
      },
      {
        id: "rbc-avion-platinum",
        name: "RBC Avion Visa Platinum",
        tag: "Special offer",
        headline: "Get up to 55,000 Avion points (max travel value of $1,100 — up to 3 round-trip flights). No minimum income required to apply.",
        bullets: [
          "Earn 1 Avion point on everyday purchases.",
          "Book travel on any airline, any flight, any time.",
          "Travel insurance coverage including trip cancellation.",
          "Additional card: $50.",
        ],
        annualFee: "$120",
        purchaseRate: "20.99%",
        cashRate: "22.99%",
      },
    ],
  },
];
